version: '3'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.1
    volumes:
      - "kafka_data1:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=host.docker.internal
      - KAFKA_AUTO_LEADER_REBALANCE_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka2:
    image: docker.io/bitnami/kafka:3.1
    volumes:
      - "kafka_data2:/bitnami"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=host.docker.internal
      - KAFKA_AUTO_LEADER_REBALANCE_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9009:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka

  redis:
    image: redis:3.2.3-alpine
    restart: on-failure
    ports:
      - "6380:6379"

  php:
    build: .
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_XDEBUG_MODE=${XDEBUG_MODE:-off}
      - NGINX_CACHE_ENABLE=0
      - PHP_DISPLAY_ERRORS=On
      - APP_ENV=dev
      - SYMFONY_ENV=dev
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - kafka
      - zookeeper
      - redis

volumes:
  zookeeper_data:
    driver: local
  kafka_data1:
    driver: local
  kafka_data2:
    driver: local
