framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn:  "%env(MESSENGER_TRANSPORT_DSN)%"
            failed:
                dsn: "file://failed.txt"

        routing:
            'App\Message\LogNotification': async
